config/routes.rb
DKENetwork::Application.routes.draw do
  resources :comments
  resources :pins do

    resources :comments
  end

  resources :pins

  get "users/show"

  devise_for :users
  match 'users/:id' => 'users#show', as: :user

  get "pages/home"

  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'
  

  root :to => 'pins#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :pin_id
  belongs_to :pin
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :title, :body, :image, :image_remote_url

  validates :body, presence: true
  validates :user_id, presence: true
  has_attached_file :image, styles: { medium: "320x240>"}
	validates_attachment :image, #presence: true,
                            content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
                            size: { less_than: 5.megabytes }

  belongs_to :user
  has_many :comments

  def image_remote_url=(url_value)
  	self.image = URI.parse(url_value) unless url_value.blank?
  	super
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable, 
  	:rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :phone_number, :password, :password_confirmation, :remember_me, :first_name, :last_name, :chapter, :year, :address, :occupation, :title, :company, :industry, :city, :state_or_province, :postal_code, :job_description
  # attr_accessible :title, :body

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def create
  @pin = Pin.find(params[:pin_id])
  @comment = @pin.comments.create(params[:comment])

  respond_to do |format|
    if @comment.save
      format.html { redirect_to @pin, notice: 'Comment was successfully created.' }
      format.json { render json: @comment, status: :created, location: @comment }
    else
      format.html { render action: "new" }
      format.json { render json: @comment.errors, status: :unprocessable_entity }
    end
  end
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def action
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc").page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@pins = @user.pins
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
	<p>
		<small>Posted <%= time_ago_in_words(comment.created_at) %> ago </small>
		<br>
		<strong><%= h(comment.body) %></strong>
	</p>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for(@comment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :pin_id %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Pin</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.pin_id %></td>
    <td><%= comment.body %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pin:</b>
  <%= @comment.pin_id %>
</p>

<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
	For more information on Delta Kappa Epsilon, click <%= link_to "here", "http://dke.org" %>.
	</small>
	<br>
	<small>
		<%= link_to 'Home',  root_path %> | <%= link_to 'About',  about_path %> | <%= link_to "Contact", contact_path %>
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
             <a class="brand" href="/">&Delta;&Kappa;&Epsilon;Network | <font size="1">Your Connetion to Dekes Around the Globe.</font></a>
                <div class="nav-collapse">
                    <ul class="nav pull-right">
                            <% if user_signed_in? %>
                                <li><%= link_to "Add Post", new_pin_path %></li>
                                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                                <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                            <% else %>
                                <li><%= link_to 'Login', new_user_session_path %></li>
                            <% end %>
                    </ul>
                </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>DKENetwork</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
<%= render 'layouts/header' %>
	<div class="container">
			<% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    	<% end %>
    	<%= yield %>
    	<%= render 'layouts/footer' %>
    </div>
	</body>
</html>

app/views/pages/_home.html.erb
<% unless user_signed_in? %>
    <div class="hero-unit">
  <h1>Welcome to &Delta;&Kappa;&Epsilon;Network.</h1>
  <p>Your connection to Dekes around the globe.</p>
  <p>
      <%= link_to 'Create an Account', new_user_registration_path, class: "btn btn-primary btn-large" %>
      <%= link_to 'Login', new_user_session_path, class: "btn btn-primary btn-large" %>
        </p>
    </div>
<% end %>

app/views/pages/about.html.erb
<div class="hero-unit">
  <h1>About &Delta;&Kappa;&Epsilon;Network.</h1>
  <p>&Delta;&Kappa;&Epsilon;Network is the official networking site for the brothers of Delta Kappa Epsilon International Fraternity.
  <br>As a brotherhood, one of our greatest assets is ourselves. With over 40,000 living alumni and active brothers, it doesn't matter where your interests lie; chances are, there's a brother who has already been through it and is willing to lend his wisdom and guidance. The purpose of &Delta;&Kappa;&Epsilon;Network is to connect Dekes with Dekes around the globe so as to strengthen our bonds and help eachother reach our full potential. 
  <br>In the bonds - Welcome to &Delta;&Kappa;&Epsilon;Network. </p>
  <p>
      <%= link_to 'Create an Account', new_user_registration_path, class: "btn btn-primary btn-large" %>
  </p>
</div>

app/views/pages/contact.html.erb
<div class="hero-unit">
  <h1>Contact &Delta;&Kappa;&Epsilon;Network.</h1>
  <p>For questions or more information regarding &Delta;&Kappa;&Epsilon;Network, please contact:</p>
	<p>drake@dke.org
	<br>(734) 302-4210</p>
</div>

app/views/pages/home.html.erb
<div class="hero-unit">
  <h1>Welcome to &Delta;&Kappa;&Epsilon;Network.</h1>
  <p>Your connection to Dekes around the globe.</p>
  <p>
      <%= link_to 'Create an Account', new_user_registration_path, class: "btn btn-primary btn-large" %>
  </p>
</div>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  	<%= f.input :title %>
    <%= f.input :body, as: :text, input_html: {rows: "3"} %>
    <%= f.input :image, label: "Upload an image" %>
    <%= f.input :image_remote_url, label: "or enter a URL" %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
		<h4> <%= link_to pin.title, pin %> </h4> 
			<% if pin.image.file? %>
			<%= image_tag pin.image(:medium) %>
			<% end %>
			<p><%= pin.body %></p>
			<p>
				<strong>
				Posted by Brother <%= link_to pin.user.last_name, pin.user %>
				</strong>
			<p>
		<% if current_user == pin.user %>
			<%= link_to 'Edit', edit_pin_path(pin) %>
			<%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %></p>
	<% end %>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<% if user_signed_in? %>
<div id="pins">
    <%= render @pins %>
</div>
    <%= will_paginate @pins %>
<% else %>
<%= render 'pages/home' %>
<% end %>

app/views/pins/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<p>
		  	<b>Description:</b>
		  	<%= @pin.body %>
			</p>
			<%= image_tag @pin.image %>
			<% if current_user == @pin.user %>
			<%= link_to 'Edit', edit_pin_path(@pin) %> |
			<% end %>
			<%= link_to 'Back', pins_path %>
		</div>
			<h4>Comments</h4>
				<div id="comments">
					<%= render :partial => @pin.comments %>
				</div>
					<%= simple_form_for [@pin, Comment.new] do |f| %>
						<p>
							<%= f.input :body, :label => "New Comment", as: :text, input_html: { rows: "3" } %>
						<p>
					 		<%= f.submit "Add Comment", class: "btn btn-primary" %>
					 	</p>
					<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="well">
	<center><h1><%= @user.first_name %> <%= @user.last_name %></h1>
	<h3><%= @user.chapter %>, <%= @user.year %></h3>
	<h4><%= @user.email %></h4>
	<h4><%= @user.phone_number %></h4>
	<h4><%= @user.address %></h4>
	<h4><%= @user.city %>, <%= @user.state_or_province %> <%= @user.postal_code %></h4></center>
</div>

<div class="well">
	<center><h3><%= @user.title %></h3>
	<h3><%= @user.company %></h3>
	<p><%= @user.job_description %></p></center>
</div>

<div id="pins">
	<%= render @pins %>
</div>